# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "maiat-trust-score-staging"
    workflow-artifacts:
      workflow-path: "./main.ts"
      config-path: "./config.staging.json"
      secrets-path: ""
# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "maiat-trust-score-production"
    workflow-artifacts:
      workflow-path: "./main.ts"
      config-path: "./config.production.json"
      secrets-path: ""
